<a href="https://colab.research.google.com/github/heyaankit/pdm-industrial-app/blob/main/notebooks/1_pump_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# necessary imports

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Loading dataset

df = pd.read_csv('drive/MyDrive/Datasets/PdM Dataset/Large_Industrial_Pump_Maintenance_Dataset.csv')

In [5]:
df.head(3)

,Pump_ID,Temperature,Vibration,Pressure,Flow_Rate,RPM,Operational_Hours,Maintenance_Flag
0,2,127.508350,2.369397,136.021029,6.501492,1444.191922,3966.793672,1
1,4,88.975185,4.541126,147.516973,7.001516,1004.802496,3673.288933,0
2,3,61.832325,2.542112,220.858577,8.824368,2597.662712,5489.061016,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Pump_ID            20000 non-null  int64
 1   Temperature        20000 non-null  float64
 2   Vibration          20000 non-null  float64
 3   Pressure           20000 non-null  float64
 4   Flow_Rate          20000 non-null  float64
 5   RPM                20000 non-null  float64
 6   Operational_Hours  20000 non-null  float64
 7   Maintenance_Flag   20000 non-null  int64
dtypes: float64(6), int64(2)
memory usage: 1.2 MB

In [8]:
df.isnull().sum()

Pump_ID              0
Temperature          0
Vibration            0
Pressure             0
Flow_Rate            0
RPM                  0
Operational_Hours    0
Maintenance_Flag     0
dtype: int64